modLoader = "lowcodefml"
loaderVersion = "[46,)"
license = "LGPLv3"

[[mods]]
modId = "mifb"
version = "${version}"
displayName = "Minecraft Isn't For Babies"
displayURL = "https://discord.gg/MTUHt3r"
logoFile = "icon.png"
authors = "Ordana"
description = "A mod to prevent Baby Zombies from spawning"

[[dependencies.mifb]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mifb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
